apiVersion: v1
kind: Secret
metadata:
  name: omyfish-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "omyfish.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: {{ .Values.secrets.datasourceUsername | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secrets.datasourcePassword | quote }}
  SPRING_RABBITMQ_USERNAME: {{ .Values.secrets.rabbitmqUsername | quote }}
  SPRING_RABBITMQ_PASSWORD: {{ .Values.secrets.rabbitmqPassword | quote }}
  MINIO_ACCESS_KEY: {{ .Values.secrets.minioAccessKey | quote }}
  MINIO_SECRET_KEY: {{ .Values.secrets.minioSecretKey | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
